name: mi439 Kernel Compiler

on: 
  push:
    branches:
      - a12/main

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    container: 
      image: jprimero15/archlinux-docker:latest

    steps:
    - uses: actions/checkout@v2
    - name: Building mi439 Kernel
      env:
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }} 
    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      with:
          name: ${{env.Rec_name}}_for_${{env.device}}-${{github.run_id}}
          path: ${{steps.info.outputs.OutFolder}}/*.Image.gz-dtb
    - name: Upload Release
      uses: softprops/action-gh-release@master
      with:
          files: |
            ${{steps.info.outputs.OutFolder}}/${{env.Rec_name}}_for_${{env.device}}_by_${{env.Author}}.zip
            ${{steps.info.outputs.OutFolder}}/*.img
          name: ${{env.Rec_name}}-${{env.device}}-${{github.run_id}}
          tag_name: ${{env.device}}-${{env.Rec_name}}-${{steps.info.outputs.date}}
          body: |
            ${{env.Rec_name}}-${{env.Rec_ver}} for ${{env.device}} build at ${{steps.info.outputs.date}}
            Actions:[${{github.run_id}}](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}})
            Download:[${{env.Rec_name}}_for_${{env.device}}_by_${{env.Author}}.zip](https://download.fastgit.org/${{github.repository}}/releases/download/${{env.device}}-${{env.Rec_name}}-${{steps.info.outputs.date}}/${{env.Rec_name}}_for_${{env.device}}_by_${{env.Author}}.zip)
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: (github.event.inputs.Delete_oldReleases == 'true' && github.event.inputs.Delete_oldReleases  != 'false') || contains(github.event.action, 'Delete_oldReleases')
      with:
          keep_latest: 12
          delete_tags: true
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
          keep_minimum_runs: 10
