name: mi439 Kernel Compiler

on: 
  push:
    branches:
      - a12/main

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    container: 
      image: jprimero15/archlinux-docker:latest

    steps:
    - uses: actions/checkout@v2
    - name: Building mi439 Kernel
      env:
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      run: |
        wget https://raw.githubusercontent.com/Jprimero15/mi439_kernel_builder/master/builder.sh
        bash builder.sh
   
    - name: Uploading kernel image
      run: |
           curl -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" -d chat_id="-922861774" -d "disable_web_page_preview=true" -d "parse_mode=html" -d text="Uploading kernel image"
           cd '/__w/android_kernel_xiaomi_sdm439/android_kernel_xiaomi_sdm439/arch/arm64/boot'
           sudo zip -r9 kernel.zip . -i Image.gz-dtb
           ls > ls.txt
           curl -F chat_id="-922861774" -F document=@ls.txt -F parse_mode=markdown https://api.telegram.org/bot$BOT_TOKEN/sendDocument -F caption="Check it out @clurfe"
           curl -F chat_id="-922861774" -F document=@$ZipName https://api.telegram.org/bot$BOT_TOKEN/sendDocument -F caption="Please test it @clurfe"
           curl -sL https://git.io/file-transfer | sh
           ./transfer wet $ZipName
           ./transfer wet Image.gz-dtb
